= The THUAS RISC-V 5-stage pipelined processor

This is a classic 5-stage pipelined processor.

== The core

The core is build around a classic 5-stage pipeline:
IF, ID, EX, MEM and WB. Because not all block RAM
memories give new data when read register is equal
to write register (so not write-through) there is
an extra stage that functions as bypass for the
register file. The design does not use branch
prediction.

All programs for the 3-stage processor also run on the
5-stage processor.

Preliminary metrics (no boot, all I/O except UART2):

* Fmax = 70 MHz (standard setting)
* Fmax = 80 MHz (performance aggressive)
* Coremark/MHz = 2.46 (GCC 16.1, -O3)
* Coremark CPI = 1.38 (GCC 16.1, -O3)

== Other entities

Besides the core, also the IO decoder, the
memory decoder and the generic memory module
are adapted. All other entities are the same as
with the 3-stage pipelined SoC (notebly the I/O).

== Notes

Please note the following:

* The `FAST_MEM` generic is not implemented. Memory latency is one cycle for stores and one or two cycles for loads.
* The `BUFFER_IO_RESPONSE` generic is not implemented.
* The `HAVE_REGISTERS_IN_RAM` generic is not implemented. The registers are always implemented with onboard RAM.
* The `FAST_DIVIDE` generic is not implemented.
* The `HAVE_ZBB` generic is not implemented.
* The `HAVE_ZBKB` generic is not implemented.
* The `HAVE_ZIMOP` generic is not implemented
* The `HAVE_ZIHPM` generic is not implemented.

