= The THUAS RISC-V 5-stage pipelined processor

*preliminary*

This is an implementation of the THUAS RISC-V RV32IM SoC using a classic 5-stage pipelined core. The core implements the 32-bit integer (I) and multiplication/division (M) extensions, the Zicsr and Zicntr extensions, and optionally the Zba en Zbs extensions. The SoC can be equipped with a bootloader to upload programs to memory and/or an on-chip debugger to debug the SoC using the JTAG protocol. The on-chip debugger works with OpenOCD, GDB and Eclipse-CDT.

All instructions from the "The RISC-V Instruction Set Manual Volume I, Unprivileged Architecture, Version 20260120", RV32I, are supported, so including `fence` and `hint` which act as no-ops, and `ecall` and `ebreak`.  From the "The RISC-V Instruction Set Manual: Volume II Privileged Architecture, Version 20260120", Machine-Level ISA, Version 1.13, `mret` and `wfi` are supported. The microcontroller supports Machine mode only. Traps (interrupts and exceptions) are supported.

Current Coremark testbench shows a CPI of 1.38 and a score of 2.46 coremarks/MHz (GCC 16.1, -O3). The SoC is developed on a Altera https://www.intel.com/content/www/us/en/products/details/fpga/cyclone/v.html[Cyclone V FPGA] using the Terasic https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&No=921[DE0-CV board]. The current $f_{max}$ is 70+ MHz (standard setting) and 80+ MHz (performance aggressive).

== The core

The core is build around a classic 5-stage pipeline: IF, ID, EX, MEM and WB. Because not all block RAM memories give new data when read register is equal to write register (so not write-through) there is an extra stage that functions as bypass for the register file. The design does not use branch prediction.

All programs for the https://github.com/jesseopdenbrouw/thuas-riscv[3-stage processor] also run on the 5-stage processor.

Instruction execution times:

* Load: 1 clock (normal) or 2 clocks (use-after-load)
* Store: 1 clock
* Branch taken: 3 clocks
* Branch not taken: 1 clock
* Jumps: 3 clocks
* Multiplication: 3 clocks
* Division: 34 clocks
* ECALL, EBREAK: 4 clocks
* CSR: 1 clock
* All other instructions: 1 clock

An trap taken takes 4 clocks, a return from the handler takes 3 clocks. Note that multi-cycle operations cannot be interrupted.

When the on-chip debugger is used, the halt state is typically reached in 3 clocks. A resume from halt takes 4 clocks.

== Other entities

Besides the core, also the IO decoder, the
memory decoder and the generic memory module
are adapted. All other entities are the same as
with the 3-stage pipelined SoC (notebly the I/O).

== Bootloader and On-Chip Debugger

The bootloader and on-chip debugger work the same
as with the 3-stage pipelined processor.

== Notes

Please note the following:

* The `FAST_MEM` generic is not implemented. Memory latency is one cycle for stores and one or two cycles for loads.
* The `BUFFER_IO_RESPONSE` generic is not implemented.
* The `HAVE_REGISTERS_IN_RAM` generic is not implemented. The registers are always implemented with onboard RAM.
* The `FAST_DIVIDE` generic is not implemented.
* The `HAVE_ZBB` generic is not implemented.
* The `HAVE_ZBKB` generic is not implemented.
* The `HAVE_ZIMOP` generic is not implemented
* The `HAVE_ZIHPM` generic is not implemented.

